/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorTelefono;
import ec.edu.ups.modelo.Persona;
import ec.edu.ups.modelo.Telefono;


/**
 *
 * @author santi
 */
public class VistaPrincipal extends javax.swing.JFrame {

    
    ControladorTelefono<Persona>controladorTelefono;
    ControladorTelefono<Telefono>controladorTelefono1;
    VistaGestionUsuario vistaGestionUsuario;
    VistaGestionTelefono vistaGestionTelefono;
    
    public VistaPrincipal() {
        initComponents();
        
        controladorTelefono = new ControladorTelefono();
        controladorTelefono1 = new ControladorTelefono();
        vistaGestionUsuario = new VistaGestionUsuario(controladorTelefono);
        vistaGestionTelefono = new VistaGestionTelefono(controladorTelefono1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        FileInicio = new javax.swing.JMenu();
        itemGestionTelefono = new javax.swing.JMenuItem();
        itemGestionUsuario = new javax.swing.JMenuItem();
        itemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FileInicio.setForeground(new java.awt.Color(255, 51, 51));
        FileInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/ups/edu/imagenes/casa.png"))); // NOI18N
        FileInicio.setMnemonic('f');
        FileInicio.setText("Inicio");

        itemGestionTelefono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/ups/edu/imagenes/carpeta (1).png"))); // NOI18N
        itemGestionTelefono.setMnemonic('o');
        itemGestionTelefono.setText("Gestion Telefono");
        itemGestionTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestionTelefonoActionPerformed(evt);
            }
        });
        FileInicio.add(itemGestionTelefono);

        itemGestionUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/ups/edu/imagenes/sistema-de-gestion-de-contenidos.png"))); // NOI18N
        itemGestionUsuario.setMnemonic('s');
        itemGestionUsuario.setText("Gestion Usuario");
        itemGestionUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGestionUsuarioActionPerformed(evt);
            }
        });
        FileInicio.add(itemGestionUsuario);

        itemSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/ups/edu/imagenes/entrar.png"))); // NOI18N
        itemSalir.setMnemonic('x');
        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        FileInicio.add(itemSalir);

        menuBar.add(FileInicio);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemSalirActionPerformed

    private void itemGestionUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestionUsuarioActionPerformed
        
        desktopPane.add(vistaGestionUsuario);
        vistaGestionUsuario.setVisible(true);
        
    }//GEN-LAST:event_itemGestionUsuarioActionPerformed

    private void itemGestionTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGestionTelefonoActionPerformed

        desktopPane.add(vistaGestionTelefono);
        vistaGestionTelefono.setVisible(true);

    }//GEN-LAST:event_itemGestionTelefonoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu FileInicio;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem itemGestionTelefono;
    private javax.swing.JMenuItem itemGestionUsuario;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
